name: JavaScript Deobfuscator

on:
  push:
    paths:
      - '**.js' 
  workflow_dispatch:
    inputs:
      file_path:
        description: 'Path to JavaScript file to deobfuscate'
        required: true
        type: string
        default: 'filejsclient.js'

permissions:
  contents: write
  pull-requests: write

jobs:
  deobfuscate:
    runs-on: ubuntu-latest
    
    steps:
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}

      - name: Setup Node.js & Python
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jsbeautifier esprima rich click

      # Setup deobfuscator như cũ
      - name: Create deobfuscator directory 
        run: |
          mkdir -p deobfuscator/src
          chmod 755 deobfuscator/src
        
      - name: Setup deobfuscator scripts
        shell: bash
        run: |
          cat << 'EOL' > deobfuscator/src/cli.py
          ${{ secrets.DEOBFUSCATOR_CLI }}
          EOL
          chmod 644 deobfuscator/src/cli.py
          
          cat << 'EOL' > deobfuscator/src/__init__.py
          ${{ secrets.DEOBFUSCATOR_INIT }}
          EOL
          chmod 644 deobfuscator/src/__init__.py

      # Giữ lại 1000 dòng logic xử lý trước
      - name: Process with previous logic
        run: |
          file="${{ github.event.inputs.file_path }}"
          python -m deobfuscator.src.cli "$file" \
            --chunk-size 1000 \
            --verbose \
            --output "${file%.js}.step1.js"

      # Thêm bước dùng Copilot phân tích
      - name: Setup Copilot
        uses: github/copilot@v1
      
      - name: Analyze with Copilot
        run: |
          # Input là file đã qua bước 1
          input="${{ github.event.inputs.file_path }}.step1.js"
          
          # Dùng Copilot phân tích từng phần
          copilot analyze "$input" \
            --explain \
            --translate \
            --output "${input%.js}.analyzed.md"
          
          # Thêm comments giải thích vào code
          copilot explain "$input" \
            --verbose \
            --output "${input%.js}.explained.js"

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: analyzed-js
          path: |
            *.step1.js
            *.analyzed.md
            *.explained.js

      - name: Create PR 
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PAT }}
          commit-message: "feat: analyze js with copilot"
          title: 'Analyzed JavaScript'
          body: |
            Files processed:
            1. Deobfuscated with previous 1000 lines logic
            2. Analyzed with Copilot
            3. Added detailed explanations
            
            Check:
            - step1.js: Deobfuscated result
            - analyzed.md: Copilot analysis
            - explained.js: Code with comments
          branch: analyze-js
          delete-branch: true
