name: Deobfuscate with Copilot

on:
  workflow_dispatch:
    inputs:
      file_path:
        description: 'Path to JavaScript file'
        required: true
        default: 'filejsclient.js'

permissions:
  contents: write
  pull-requests: write

jobs:
  deobfuscate:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
          
      - uses: github/copilot@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Deobfuscate with Copilot
        run: |
          # Use Copilot to analyze and translate the code
          copilot analyze ${{ github.event.inputs.file_path }} \
            --translate \
            --output ${{ github.event.inputs.file_path }}.deob.js

      - name: Create PR
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PAT }}
          commit-message: "deobfuscate with copilot"
          title: 'Deobfuscated with Copilot'
          body: 'Deobfuscated and translated using GitHub Copilot'
          branch: deob
          delete-branch: true
