name: JavaScript Processor

on:
  workflow_dispatch:
    inputs:
      files:
        description: 'Files to process (comma separated)'
        required: true
        default: 'filejsclient.js'

permissions:
  contents: write
  pull-requests: write

jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Create requirements
        run: |
          echo "click==8.1.7" > requirements.txt
          echo "jsbeautifier==1.14.11" >> requirements.txt
          echo "esprima==4.0.1" >> requirements.txt
          pip install -r requirements.txt

      - name: Create deobfuscator script
        run: |
          mkdir -p deobfuscator/src
          cat > deobfuscator/src/__init__.py << 'EOL'
          # Init file
          EOL
          
          cat > deobfuscator/src/cli.py << 'EOL'
          import click
          import jsbeautifier
          import esprima
          
          @click.command()
          @click.argument('input_file')
          @click.option('--output', help='Output file')
          def process(input_file, output):
              # Đọc file input
              with open(input_file, 'r') as f:
                  code = f.read()
              
              # Logic xử lý 1000 dòng ở đây
              processed = jsbeautifier.beautify(code)
              
              # Ghi ra file output
              out_file = output or input_file + '.deob.js'
              with open(out_file, 'w') as f:
                  f.write(processed)
                  
          if __name__ == '__main__':
              process()
          EOL

      - name: Process files
        run: |
          IFS=',' read -ra files <<< "${{ github.event.inputs.files }}"
          for file in "${files[@]}"; do
            file=$(echo "$file" | xargs)
            if [ -f "$file" ]; then
              echo "Processing $file..."
              python -m deobfuscator.src.cli "$file" --output "${file%.js}.deob.js"
            fi
          done

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          delete-branch: true
          branch: deob-js
          title: 'Deobfuscate JavaScript'
          commit-message: 'feat: deobfuscate js'
          body: |
            Processed files:
            ${{ github.event.inputs.files }}
