name: JavaScript Deobfuscator

on:
  workflow_dispatch:
    inputs:
      file_path:
        description: 'Path to JavaScript file'
        required: true
        default: 'filejsclient.js'

permissions:
  contents: write
  pull-requests: write

jobs:
  deobfuscate:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install GitHub CLI & Copilot
        run: |
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt update
          sudo apt install gh
          gh extension install github/gh-copilot
          
      - name: Process & Analyze
        run: |
          file="${{ github.event.inputs.file_path }}"
          
          # 1. Deobfuscate (1000 dòng logic cũ)
          python -m deobfuscator.src.cli "$file" --output "${file%.js}.step1.js"
            
          # 2. Dùng Copilot phân tích
          gh copilot explain "${file%.js}.step1.js" > "${file%.js}.analyzed.md"
          gh copilot suggest "${file%.js}.step1.js" > "${file%.js}.explained.js"

      - uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PAT }}
          commit-message: "feat: analyze js"
          title: 'Analyzed JavaScript'
          branch: analyze-js
          delete-branch: true
